# 03 · Las diferencias que sobreviven

**Objetivo:** Medir cuánto de una diferencia de precio entre municipios se mantiene cuando se comparan productos, presentaciones y periodos equivalentes, y distinguir lo que los datos públicos permiten afirmar de lo que haría falta para evaluar una oportunidad de negocio.

**Pregunta:** ¿Qué diferencias sobreviven, en qué productos y municipios, y con qué incertidumbre?

Por qué importa: una diferencia que sobrevive a la validación y a la prueba contra el azar es la única que
vale la pena investigar con costos, márgenes y demanda.

**Decisión:** para cada artículo comparable (mismo nombre, presentación, marca y giro, con 3 tiendas o más en 10
municipios o más) se prueba si sus precios de tienda difieren entre municipios más que entre tiendas del mismo
municipio (Kruskal-Wallis), con control de falsos positivos de Benjamini-Hochberg al 10%. Alternativa descartada: la
prueba sin corrección, que con más de mil artículos declara «distintos» a unos 50 solo por azar.

In [1]:
import os
for _v in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS"):
    os.environ.setdefault(_v, "1")
from pathlib import Path
import sys, json
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display, Markdown

ROOT = Path.cwd()
if ROOT.name == "notebooks":
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT / "src"))
import entorno
entorno.setup()
import profeco, tablas, estadistica as E, charts as C
import embudo as M
PROC, META, CHARTS, SOCIAL = entorno.PROC, entorno.META, entorno.CHARTS, entorno.SOCIAL
CFG = entorno.config()
def reg(*a, **k):
    entorno.registrar(*a, **k)
pd.set_option("display.max_columns", 30)
pd.set_option("display.width", 220)
pd.set_option("display.max_colwidth", 70)
raw = entorno.load_raw()
d_all = M.prep(raw)
d = d_all[~d_all.catalogo.isin(M.FUERA_PRINCIPAL)].copy()      # universo principal
params = json.loads((META / "parametros.json").read_text(encoding="utf-8"))
REPS = params.get("bootstrap_replicas", 500)
C.register_cities(d_all.municipio_id.unique())
res, prod, un, pm = M.embudo(d)
U = set(prod.index)
fin = un["extremos"][un["extremos"].producto.isin(U)]
sp = M.tiendas_finales(d).merge(fin[M.UNIDAD], on=M.UNIDAD)
kw = M.prueba_municipio(sp)
kw["sobrevive"] = M.bh(kw.p_valor, params["fdr"])
ic = M.boot_unidad(pm["extremos"].merge(fin[M.UNIDAD], on=M.UNIDAD), reps=REPS)
mc = M.misma_cadena(sp).rename(columns={"brecha_pct": "misma_cadena_pct"})[M.UNIDAD + ["misma_cadena_pct"]]
az = pd.read_csv(PROC / "azar_unidades.csv", encoding="utf-8-sig", dtype=str, keep_default_na=False)
for c in ["brecha_pct", "azar_mediana", "azar_p95", "p_azar", "exceso_pp"]:
    az[c] = az[c].astype(float)
f = (fin.merge(kw, on=M.UNIDAD).merge(ic, on=M.UNIDAD).merge(mc, on=M.UNIDAD, how="left")
        .merge(az[M.UNIDAD + ["azar_mediana", "azar_p95"]], on=M.UNIDAD, how="left"))
info = d.groupby(M.UNIDAD).agg(catalogo=("catalogo", "first"), categoria=("categoria", "first")).reset_index()
f = f.merge(info, on=M.UNIDAD, how="left")
F = "03_diferencias_que_sobreviven"
print(f"Artículos comparables: {len(f):,} · p<0.05 sin corrección: {(f.p_valor < .05).sum()} · sobreviven con corrección: {f.sobrevive.sum()}")
reg("n_articulos", len(f), fuente=F)
reg("n_sobreviven", f.sobrevive.sum(), n=len(f), fuente=F, nota="artículos con diferencia entre municipios tras Benjamini-Hochberg 10%")
reg("pct_sobreviven", f.sobrevive.mean() * 100, n=len(f), fuente=F)
reg("n_p05", (f.p_valor < .05).sum(), n=len(f), fuente=F)
reg("esperados_azar_p05", len(f) * 0.05, fuente=F)

Artículos comparables: 1,238 · p<0.05 sin corrección: 138 · sobreviven con corrección: 45

## 1. ¿Qué tienen en común los que sobreviven?

**Familia** = agrupación para leer el resultado: bebidas (refresco, cerveza, agua, jugo), tortilla, frescos y a granel
(frutas, verduras, carne, pan de mostrador, huevo) y otros.

In [2]:
def familia(row):
    p = row.producto.lower()
    if any(k in p for k in ["refresco", "cerveza", "agua", "jugo"]):
        return "Bebidas"
    if "tortilla" in p:
        return "Tortilla"
    if row.catalogo in ("Frutas y Legumbres", "Pescados y Mariscos", "Mercados") or any(k in p for k in ["carne", "bolillo", "huevo", "pollo"]):
        return "Frescos y a granel"
    return "Otros"
f["familia"] = f.apply(familia, axis=1)
fam = f.groupby("familia").agg(articulos=("sobrevive", "size"), sobreviven=("sobrevive", "sum"))
fam["% que sobrevive"] = fam.sobreviven / fam.articulos * 100
display(fam.round(1))
cmp_ = f.groupby("sobrevive")[["brecha_pct", "azar_mediana", "misma_cadena_pct", "municipios"]].median()
display(cmp_.round(1))
for k in fam.index:
    key = {"Bebidas": "bebidas", "Tortilla": "tortilla", "Frescos y a granel": "frescos", "Otros": "otros"}[k]
    reg(f"sob_{key}", fam.loc[k, "sobreviven"], n=fam.loc[k, "articulos"], fuente=F)
    reg(f"pct_sob_{key}", fam.loc[k, "% que sobrevive"], n=fam.loc[k, "articulos"], fuente=F)
reg("brecha_sobreviven", cmp_.loc[True, "brecha_pct"], fuente=F)
reg("brecha_no_sobreviven", cmp_.loc[False, "brecha_pct"], fuente=F)
reg("cadena_sobreviven", cmp_.loc[True, "misma_cadena_pct"], fuente=F, nota="brecha entre municipios de la misma cadena, artículos que sobreviven")
reg("cadena_no_sobreviven", cmp_.loc[False, "misma_cadena_pct"], fuente=F)

                    articulos  sobreviven  % que sobrevive
familia
Bebidas                    80          22             27.5
Frescos y a granel        138          12              8.7
Otros                    1015           9              0.9
Tortilla                    5           2             40.0

           brecha_pct  azar_mediana  misma_cadena_pct  municipios
sobrevive
False            10.0           9.4               1.3        29.0
True             23.2          10.4              13.3        40.0

**Lectura.** En los artículos que sobreviven, la misma cadena también cobra distinto según el municipio: la
diferencia no es solo qué cadenas hay en cada lugar. En los que no sobreviven, la misma cadena cobra casi igual en
todas partes.

## 2. Dónde está la diferencia: municipio caro y barato típicos

In [3]:
pmf = pm["extremos"].merge(f.loc[f.sobrevive, M.UNIDAD], on=M.UNIDAD)
def extremos_mun(g):
    g = g.sort_values("precio")
    q10, q90 = g.precio.quantile(.1), g.precio.quantile(.9)
    lo = g.iloc[(g.precio - q10).abs().argmin()]
    hi = g.iloc[(g.precio - q90).abs().argmin()]
    return pd.Series({"mun_barato": C.city(lo.municipio_id), "precio_barato": lo.precio, "mun_caro": C.city(hi.municipio_id),
                      "precio_caro": hi.precio, "mediana": g.precio.median()})
ext = pmf.groupby(M.UNIDAD).apply(extremos_mun, include_groups=False).reset_index()
sob = f[f.sobrevive].merge(ext, on=M.UNIDAD)
# Relevante: además de pasar la prueba, la diferencia es de 10% o más y su IC90 queda arriba de lo típico del azar.
sob["relevante"] = (sob.brecha_pct >= M.MIN_RELEVANTE) & (sob.ic90_inf > sob.azar_mediana)
sob["etiqueta"] = [M.etiqueta(a, b_, c_, e_) for a, b_, c_, e_ in zip(sob.producto, sob.pres_key, sob.marca, sob.presentacion)]
sob = sob.sort_values(["relevante", "p_valor"], ascending=[False, True])
cols = ["etiqueta", "producto", "pres_key", "presentacion", "marca", "giro", "familia", "municipios", "brecha_pct", "ic90_inf", "ic90_sup",
        "azar_mediana", "azar_p95", "misma_cadena_pct", "mun_barato", "precio_barato", "mun_caro", "precio_caro", "p_valor", "relevante"]
display(sob[cols].round(2))
rel = sob[sob.relevante]
reg("n_relevantes", len(rel), n=len(sob), fuente=F, nota="sobreviven, brecha >= 10% e IC90 inferior arriba de la mediana del azar")
for fam_, key in [("Bebidas", "bebidas"), ("Tortilla", "tortilla"), ("Frescos y a granel", "frescos"), ("Otros", "otros")]:
    reg(f"rel_{key}", (rel.familia == fam_).sum(), fuente=F)
reg("brecha_relevantes", rel.brecha_pct.median(), n=len(rel), fuente=F)
reg("cadena_relevantes", rel.misma_cadena_pct.median(), n=len(rel), fuente=F)
f.to_csv(PROC / "articulos_prueba.csv", index=False, encoding="utf-8-sig")
sob[cols].to_csv(PROC / "sobrevivientes.csv", index=False, encoding="utf-8-sig")

,etiqueta,producto,pres_key,presentacion,marca,giro,familia,municipios,brecha_pct,ic90_inf,ic90_sup,azar_mediana,azar_p95,misma_cadena_pct,mun_barato,precio_barato,mun_caro,precio_caro,p_valor,relevante
43,"Tortilla de Maíz (1 kg, granel)",Tortilla de Maíz,1.0 kg,1 Kg. Granel,S/M,Tortillerías,Tortilla,57,46.83,36.15,50.47,18.09,21.73,46.86,Iztapalapa,20.50,Benito Juárez (Quintana Roo),29.96,0.0,True
30,Refresco Coca Cola Zero (botella 600 ml),Refresco,0.6 l,Botella 600 Ml.,Coca Cola. Zero,Supermercado / Tienda de Autoservicio,Bebidas,45,27.26,20.16,35.49,19.20,24.21,18.95,Miguel Hidalgo,16.49,San Luis Potosí,20.99,0.0,True
37,"Refresco Fresca (botella 3 lt, no retornable)",Refresco,3.0 l,Botella 3 Lt. No Retornable,Fresca,Supermercado / Tienda de Autoservicio,Bebidas,41,26.40,16.57,31.82,9.54,15.00,22.79,Benito Juárez (Ciudad de México),41.96,Culiacán,53.04,0.0,True
39,"Refresco Sprite (botella 3 lt, no retornable)",Refresco,3.0 l,Botella 3 Lt. No Retornable,Sprite,Supermercado / Tienda de Autoservicio,Bebidas,38,23.24,7.64,29.97,5.51,9.95,22.15,Benito Juárez (Ciudad de México),41.97,Hermosillo,51.17,0.0,True
16,Cerveza Tecate (paquete con 12 latas de 355 ml),Cerveza,0.355 l,Paquete con 12 Latas de 355 Ml.,Tecate,Supermercado / Tienda de Autoservicio,Bebidas,43,26.10,14.79,33.54,14.70,17.91,16.80,La Paz,172.88,Tlalnepantla,219.01,0.0,True
36,"Refresco Jarritos (botella 2 lt, no retornable, tamarindo)",Refresco,2.0 l,Botella 2 Lt. No Retornable. Tamarindo,Jarritos,Supermercado / Tienda de Autoservicio,Bebidas,40,20.30,15.75,21.12,13.79,17.38,16.10,Venustiano Carranza,24.90,Guadalajara,29.96,0.0,True
14,"Cerveza Bohemia Pilsner (canasta con 6 botellas de 355 ml, no reto...",Cerveza,0.355 l,Canasta con 6 Botellas de 355 Ml. No Retornable (Clara),Bohemia. Pilsner,Supermercado / Tienda de Autoservicio,Bebidas,41,16.38,16.22,19.43,12.45,16.23,16.21,Naucalpan de Juárez,128.92,Tampico,150.04,0.0,True
15,Cerveza Indio (paquete con 12 latas de 355 ml),Cerveza,0.355 l,Paquete con 12 Latas de 355 Ml.,Indio,Supermercado / Tienda de Autoservicio,Bebidas,32,34.50,24.84,41.81,22.28,30.90,25.74,Hermosillo,163.02,Iztapalapa,219.43,0.0,True
32,"Refresco Fresca (botella 2 lt, no retornable)",Refresco,2.0 l,Botella 2 Lt. No Retornable,Fresca,Supermercado / Tienda de Autoservicio,Bebidas,33,11.40,9.73,33.37,9.35,12.40,9.84,Tlalnepantla,30.47,León,34.07,0.0,True
4,"Alimentos Preparados Maruchan (vaso 64 gr, sopa instantánea con ca...",Alimentos Preparados,0.064 kg,Vaso 64 Gr. Sopa Instantánea con Camarón y Chile Piquín,Maruchan,Supermercado / Tienda de Autoservicio,Otros,46,26.65,23.44,35.12,22.78,26.51,24.93,Miguel Hidalgo,14.99,Tampico,18.99,0.0,True
0,Agua Sin Gas Ciel (botella 1 lt),Agua Sin Gas,1.0 l,Botella 1 Lt.,Ciel,Supermercado / Tienda de Autoservicio,Bebidas,41,24.49,12.54,25.19,9.58,12.57,18.53,Morelia,12.00,San Luis Potosí,14.93,0.0,True
23,"Lechuga (pieza, romana)",Lechuga,texto: Pieza. Romana,Pieza. Romana,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,45,38.80,36.15,47.37,33.89,37.87,25.54,Culiacán,17.90,Benito Juárez (Ciudad de México),24.87,0.0,True
26,"Nopal (1 kg, granel, sin espinas)",Nopal,1.0 kg,1 Kg. Granel. Sin Espinas,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,33,50.78,44.40,63.58,36.30,45.84,29.59,Tlalnepantla,29.75,Reynosa,44.91,0.0,True
27,Pan Blanco Bolillo (pieza),Pan Blanco Bolillo,1.0 pieza,Pieza,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,41,33.33,20.25,46.75,17.86,26.25,22.69,Nezahualcóyotl,1.80,Santiago de Querétaro,2.40,0.0,True
19,"Frijol Verde Valle (bolsa 900 gr, negro)",Frijol,0.9 kg,Bolsa 900 Gr. Negro,Verde Valle,Supermercado / Tienda de Autoservicio,Otros,35,24.75,21.66,28.18,20.68,23.61,16.86,Oaxaca de Juárez,35.00,Juárez,43.76,0.0,True
13,"Cerveza Michelob Ultra (canasta con 6 botellas de 355 ml, no retor...",Cerveza,0.355 l,Canasta con 6 Botellas de 355 Ml. No Retornable,Michelob Ultra,Supermercado / Tienda de Autoservicio,Bebidas,42,23.23,15.07,25.84,9.00,12.62,14.23,Monterrey,103.96,Aguascalientes,128.12,0.0,True
17,"Chile Fresco (1 kg, granel, habanero)",Chile Fresco,1.0 kg,1 Kg. Granel. Habanero,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,44,29.11,18.33,32.91,8.80,14.20,23.86,Mérida,126.42,Hermosillo,164.36,0.0,True
42,"Tortilla de Maíz (1 kg, granel)",Tortilla de Maíz,1.0 kg,1 Kg. Granel,S/M,Supermercado / Tienda de Autoservicio,Tortilla,47,12.40,10.97,14.40,9.10,11.30,4.42,Tuxtla Gutiérrez,12.93,Cuauhtémoc,14.50,0.0,True
11,"Carne Cerdo (1 kg, granel, pierna entera sin hueso o perni…)",Carne Cerdo,1.0 kg,1 Kg. Granel. Pierna Entera Sin Hueso o Pernil Sin Hueso,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,39,30.15,12.48,30.75,10.40,15.63,13.34,Nezahualcóyotl,91.47,Monterrey,118.97,0.0,True
24,"Limón (1 kg, granel, agrio sin semilla o persa)",Limón,1.0 kg,1 Kg. Granel. Agrio Sin Semilla o Persa,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,48,53.35,36.99,64.36,36.86,50.30,33.62,Tlalnepantla,21.86,Saltillo,33.50,0.0,True
6,"Alubia Verde Valle (bolsa 500 gr, chica)",Alubia,0.5 kg,Bolsa 500 Gr. Chica,Verde Valle,Supermercado / Tienda de Autoservicio,Otros,20,19.71,6.78,23.52,6.16,11.06,5.47,Coyoacán,36.15,Centro,43.12,0.0,True
41,"Refresco Fanta (botella 3 lt, no retornable, naranja)",Refresco,3.0 l,Botella 3 Lt. No Retornable. Naranja,Fanta,Supermercado / Tienda de Autoservicio,Bebidas,34,27.13,5.85,29.98,8.62,13.88,18.43,Cuernavaca,41.95,La Paz,53.50,0.0,False
33,"Refresco Sprite (botella 2 lt, no retornable)",Refresco,2.0 l,Botella 2 Lt. No Retornable,Sprite,Supermercado / Tienda de Autoservicio,Bebidas,33,9.88,9.72,32.32,7.65,10.45,9.96,Huixquilucan,30.97,León,34.03,0.0,False
34,"Refresco Sidral Mundet (botella 2 lt, no retornable)",Refresco,2.0 l,Botella 2 Lt. No Retornable.,Sidral Mundet,Supermercado / Tienda de Autoservicio,Bebidas,33,9.90,9.73,29.14,9.47,10.45,11.52,Atizapán de Zaragoza,30.95,Oaxaca de Juárez,34.03,0.0,False
1,"Agua Sin Gas Bonafont (garrafón 20 lt, (sólo liquido))",Agua Sin Gas,20.0 l,Garrafón 20 Lt. (Sólo Liquido),Bonafont,Supermercado / Tienda de Autoservicio,Bebidas,19,10.06,5.99,12.77,7.27,9.56,6.01,León,59.00,Benito Juárez (Ciudad de México),64.93,0.0,False
29,"Plátano (1 kg, granel, macho)",Plátano,1.0 kg,1 Kg. Granel. Macho,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,41,20.03,15.77,23.55,17.18,19.94,13.61,Campeche,34.91,Benito Juárez (Ciudad de México),41.90,0.0,False
35,"Refresco Fanta (botella 2 lt, no retornable, naranja)",Refresco,2.0 l,Botella 2 Lt. No Retornable. Naranja,Fanta,Supermercado / Tienda de Autoservicio,Bebidas,31,9.83,9.70,24.29,9.77,11.36,9.43,Benito Juárez (Ciudad de México),30.97,León,34.01,0.0,False
38,"Refresco Red Cola (botella 3 lt, no retornable)",Refresco,3.0 l,Botella 3 Lt. No Retornable,Red Cola,Supermercado / Tienda de Autoservicio,Bebidas,20,27.30,0.27,30.88,1.99,11.73,27.43,Benito Juárez (Ciudad de México),34.97,Zacatecas,44.46,0.0,False
5,"Alimentos Preparados Maruchan (vaso 64 gr, sopa instantánea, sabor...",Alimentos Preparados,0.064 kg,Vaso 64 Gr. Sopa Instantánea. Sabor a Pollo,Maruchan,Supermercado / Tienda de Autoservicio,Otros,43,26.54,18.89,27.64,19.73,25.64,19.27,Tlalnepantla,15.00,Tampico,18.99,0.0,False
22,"Jugo de Fruta Boing! (caja 1 lt, mango)",Jugo de Fruta,1.0 l,Caja 1 Lt. Mango,Boing!,Supermercado / Tienda de Autoservicio,Bebidas,43,11.84,4.92,15.95,5.75,11.47,2.19,Azcapotzalco,30.45,Hermosillo,34.07,0.0,False
21,Huevo Bachoco (paquete c/18 blanco),Huevo,18.0 pieza,Paquete C/18 Blanco,Bachoco,Supermercado / Tienda de Autoservicio,Frescos y a granel,44,15.00,12.31,27.62,13.14,15.04,5.31,Nezahualcóyotl,40.01,Solidaridad,46.03,0.0,False
25,"Limón (1 kg, granel, agrio con semilla o colima)",Limón,1.0 kg,1 Kg. Granel. Agrio con Semilla o Colima,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,49,20.64,16.46,24.78,18.28,25.35,15.64,Ecatepec de Morelos,31.41,León,37.75,0.0,False
31,"Refresco Coca Cola (botella 1 lt, no retornable)",Refresco,1.0 l,Botella 1 Lt. No Retornable,Coca Cola,Supermercado / Tienda de Autoservicio,Bebidas,31,6.89,3.32,22.01,3.90,5.53,3.45,Tijuana,30.88,Coyoacán,33.00,0.0,False
9,"Calabaza (1 kg, granel, italiana/japonesa (larga))",Calabaza,1.0 kg,1 Kg. Granel. Italiana/japonesa (Larga),S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,43,35.46,29.29,49.17,29.70,33.24,7.37,La Paz,29.01,Hermosillo,39.40,0.0,False
40,"Refresco Squirt (botella 3 lt, no retornable)",Refresco,3.0 l,Botella 3 Lt. No Retornable,Squirt,Supermercado / Tienda de Autoservicio,Bebidas,31,7.64,3.57,9.37,2.47,3.91,4.45,Santiago de Querétaro,47.49,Centro,51.12,0.0,False
20,Huevo Bachoco (paquete c/12 blanco),Huevo,12.0 pieza,Paquete C/12 Blanco,Bachoco,Supermercado / Tienda de Autoservicio,Frescos y a granel,41,13.89,12.17,49.56,12.30,17.54,5.28,Tultitlán,28.11,Morelia,32.01,0.0,False
7,"Azúcar Zulka (bolsa plástico 2 kg, estándar o morena)",Azúcar,2.0 kg,Bolsa Plástico 2 Kg. Estándar o Morena,Zulka,Supermercado / Tienda de Autoservicio,Otros,36,4.56,2.96,13.36,3.41,4.58,0.68,Miguel Hidalgo,43.96,Juárez,45.94,0.0,False
44,"Yoghurt Alpura (vaso 120 gr, fresa)",Yoghurt,0.12 kg,Vaso 120 Gr. Fresa,Alpura,Supermercado / Tienda de Autoservicio,Otros,14,0.18,0.10,0.30,0.12,0.23,0.16,Benito Juárez (Ciudad de México),8.99,Centro,9.01,0.0,False
3,"Agua con Gas Del Valle (botella 600 ml, naranj-ada fizz)",Agua con Gas,0.6 l,Botella 600 Ml. Naranj-ada Fizz,Del Valle,Supermercado / Tienda de Autoservicio,Bebidas,30,33.99,18.75,49.90,22.42,29.95,13.25,Miguel Hidalgo,13.49,San Luis Potosí,17.97,0.0,False
12,Cerveza Barrilito (canasta con 6 botellas de 325 ml),Cerveza,0.325 l,Canasta con 6 Botellas de 325 Ml.,Barrilito,Supermercado / Tienda de Autoservicio,Bebidas,46,6.57,4.65,10.96,3.70,5.67,4.54,Durango,63.09,Azcapotzalco,67.25,0.0,False
28,"Papas Fritas y Similares Sabritas (bolsa 185 gr, churrumais, con l...",Papas Fritas y Similares,0.185 kg,Bolsa 185 Gr. Churrumais. con Limoncito,Sabritas,Supermercado / Tienda de Autoservicio,Otros,31,2.91,0.30,10.82,0.37,2.52,0.27,Culiacán,41.50,Juárez,42.71,0.0,False
18,Chícharos en Lata Del Monte (lata 200 gr),Chícharos en Lata,0.2 kg,Lata 200 Gr.,Del Monte,Supermercado / Tienda de Autoservicio,Otros,12,11.07,3.97,16.04,6.35,8.53,4.27,Saltillo,11.96,Solidaridad,13.31,0.0,False
8,"Bebidas Hidratantes Powerade (botella 1 lt, naranja)",Bebidas Hidratantes,1.0 l,Botella 1 Lt. Naranja,Powerade,Supermercado / Tienda de Autoservicio,Otros,45,28.57,21.97,30.46,23.28,26.02,12.95,Coacalco,26.10,Tlaxcala,33.97,0.0,False
2,"Agua con Gas Del Valle (botella 600 ml, limon-ada, fizz)",Agua con Gas,0.6 l,Botella 600 Ml. Limon-ada. Fizz,Del Valle,Supermercado / Tienda de Autoservicio,Bebidas,32,32.22,15.94,44.04,22.32,28.92,6.33,Iztapalapa,13.53,San Luis Potosí,17.97,0.0,False
10,"Camarón (1 kg, granel, chico, sin cabeza)",Camarón,1.0 kg,1 Kg. Granel. Chico. Sin Cabeza,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,26,65.41,47.12,75.63,57.33,62.86,2.84,Durango,169.94,Coyoacán,275.57,0.0,False

## 3. Casos que sobreviven

**Decisión:** un caso por familia (bebidas, tortilla, frescos), el relevante de menor valor p en cada una. Se reporta
la brecha con su IC90 y la referencia de azar del mismo artículo.

In [4]:
casos = []
for fam_, key in [("Tortilla", "tortilla"), ("Bebidas", "bebida"), ("Frescos y a granel", "fresco")]:
    s = sob[(sob.familia == fam_) & sob.relevante]
    if not len(s):
        continue
    c = s.iloc[0]
    casos.append(c)
    giro_txt = M.giro_corto(c.giro, plural=True)
    reg(f"caso_{key}_brecha", c.brecha_pct, (c.ic90_inf, c.ic90_sup), n=c.municipios, fuente=F,
        nota=f"{c.producto} · {c.pres_key} · {c.marca} · {giro_txt}")
    reg(f"caso_{key}_nombre", f"{c.etiqueta} en {giro_txt}", fuente=F)
    reg(f"caso_{key}_mun_barato", c.mun_barato, fuente=F)
    reg(f"caso_{key}_mun_caro", c.mun_caro, fuente=F)
    reg(f"caso_{key}_municipios", c.municipios, fuente=F)
    reg(f"caso_{key}_azar", c.azar_mediana, fuente=F)
    reg(f"caso_{key}_cadena", c.misma_cadena_pct, fuente=F)
    reg(f"caso_{key}_barato", c.precio_barato, fuente=F, nota=c.mun_barato)
    reg(f"caso_{key}_caro", c.precio_caro, fuente=F, nota=c.mun_caro)
casos = pd.DataFrame(casos)
display(casos[cols].round(2))
casos[cols].to_csv(PROC / "casos_sobreviven.csv", index=False, encoding="utf-8-sig")

,etiqueta,producto,pres_key,presentacion,marca,giro,familia,municipios,brecha_pct,ic90_inf,ic90_sup,azar_mediana,azar_p95,misma_cadena_pct,mun_barato,precio_barato,mun_caro,precio_caro,p_valor,relevante
43,"Tortilla de Maíz (1 kg, granel)",Tortilla de Maíz,1.0 kg,1 Kg. Granel,S/M,Tortillerías,Tortilla,57,46.83,36.15,50.47,18.09,21.73,46.86,Iztapalapa,20.50,Benito Juárez (Quintana Roo),29.96,0.0,True
30,Refresco Coca Cola Zero (botella 600 ml),Refresco,0.6 l,Botella 600 Ml.,Coca Cola. Zero,Supermercado / Tienda de Autoservicio,Bebidas,45,27.26,20.16,35.49,19.20,24.21,18.95,Miguel Hidalgo,16.49,San Luis Potosí,20.99,0.0,True
23,"Lechuga (pieza, romana)",Lechuga,texto: Pieza. Romana,Pieza. Romana,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,45,38.80,36.15,47.37,33.89,37.87,25.54,Culiacán,17.90,Benito Juárez (Ciudad de México),24.87,0.0,True

## 4. Lo que no resultó sólido

- **Distintos pero pequeños:** pasan la prueba, pero la diferencia es menor a 10% o su IC90 toca lo típico del azar.
  Estadísticamente distintos no es lo mismo que relevantes para el negocio.
- **Distintos sin corregir:** con la prueba sin corrección (valor p < 0.05) parecerían distintos, pero no sobreviven al
  control de falsos positivos.

In [5]:
fragil = sob[~sob.relevante]
reg("sob_no_relevantes", len(fragil), n=len(sob), fuente=F, nota="sobreviven a la prueba pero con brecha < 10% o IC90 que toca la mediana del azar")
reg("p05_no_sobreviven", ((f.p_valor < .05) & ~f.sobrevive).sum(), fuente=F)
display(fragil[cols].round(2))
v = entorno.cifras()
display(Markdown(f'''**Conclusión.** De {v["n_articulos"]:,.0f} artículos comparables, **{v["n_sobreviven"]:.0f}
({v["pct_sobreviven"]:.0f}%)** tienen una diferencia entre municipios que supera la prueba con control de falsos
positivos, y solo **{v["n_relevantes"]:.0f}** con una diferencia de 10% o más claramente arriba del azar:
{v["rel_bebidas"]:.0f} bebidas, {v["rel_frescos"]:.0f} frescos, {v["rel_tortilla"]:.0f} de tortilla y {v["rel_otros"]:.0f} de otros
productos. En los que sobreviven, la misma cadena cobra {v["cadena_sobreviven"]:.0f}% más en el municipio caro típico,
contra {v["cadena_no_sobreviven"]:.1f}% en los demás. {v["p05_no_sobreviven"]:.0f} artículos parecían distintos sin corregir y
no sobreviven.'''))

,etiqueta,producto,pres_key,presentacion,marca,giro,familia,municipios,brecha_pct,ic90_inf,ic90_sup,azar_mediana,azar_p95,misma_cadena_pct,mun_barato,precio_barato,mun_caro,precio_caro,p_valor,relevante
41,"Refresco Fanta (botella 3 lt, no retornable, naranja)",Refresco,3.0 l,Botella 3 Lt. No Retornable. Naranja,Fanta,Supermercado / Tienda de Autoservicio,Bebidas,34,27.13,5.85,29.98,8.62,13.88,18.43,Cuernavaca,41.95,La Paz,53.50,0.0,False
33,"Refresco Sprite (botella 2 lt, no retornable)",Refresco,2.0 l,Botella 2 Lt. No Retornable,Sprite,Supermercado / Tienda de Autoservicio,Bebidas,33,9.88,9.72,32.32,7.65,10.45,9.96,Huixquilucan,30.97,León,34.03,0.0,False
34,"Refresco Sidral Mundet (botella 2 lt, no retornable)",Refresco,2.0 l,Botella 2 Lt. No Retornable.,Sidral Mundet,Supermercado / Tienda de Autoservicio,Bebidas,33,9.90,9.73,29.14,9.47,10.45,11.52,Atizapán de Zaragoza,30.95,Oaxaca de Juárez,34.03,0.0,False
1,"Agua Sin Gas Bonafont (garrafón 20 lt, (sólo liquido))",Agua Sin Gas,20.0 l,Garrafón 20 Lt. (Sólo Liquido),Bonafont,Supermercado / Tienda de Autoservicio,Bebidas,19,10.06,5.99,12.77,7.27,9.56,6.01,León,59.00,Benito Juárez (Ciudad de México),64.93,0.0,False
29,"Plátano (1 kg, granel, macho)",Plátano,1.0 kg,1 Kg. Granel. Macho,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,41,20.03,15.77,23.55,17.18,19.94,13.61,Campeche,34.91,Benito Juárez (Ciudad de México),41.90,0.0,False
35,"Refresco Fanta (botella 2 lt, no retornable, naranja)",Refresco,2.0 l,Botella 2 Lt. No Retornable. Naranja,Fanta,Supermercado / Tienda de Autoservicio,Bebidas,31,9.83,9.70,24.29,9.77,11.36,9.43,Benito Juárez (Ciudad de México),30.97,León,34.01,0.0,False
38,"Refresco Red Cola (botella 3 lt, no retornable)",Refresco,3.0 l,Botella 3 Lt. No Retornable,Red Cola,Supermercado / Tienda de Autoservicio,Bebidas,20,27.30,0.27,30.88,1.99,11.73,27.43,Benito Juárez (Ciudad de México),34.97,Zacatecas,44.46,0.0,False
5,"Alimentos Preparados Maruchan (vaso 64 gr, sopa instantánea, sabor...",Alimentos Preparados,0.064 kg,Vaso 64 Gr. Sopa Instantánea. Sabor a Pollo,Maruchan,Supermercado / Tienda de Autoservicio,Otros,43,26.54,18.89,27.64,19.73,25.64,19.27,Tlalnepantla,15.00,Tampico,18.99,0.0,False
22,"Jugo de Fruta Boing! (caja 1 lt, mango)",Jugo de Fruta,1.0 l,Caja 1 Lt. Mango,Boing!,Supermercado / Tienda de Autoservicio,Bebidas,43,11.84,4.92,15.95,5.75,11.47,2.19,Azcapotzalco,30.45,Hermosillo,34.07,0.0,False
21,Huevo Bachoco (paquete c/18 blanco),Huevo,18.0 pieza,Paquete C/18 Blanco,Bachoco,Supermercado / Tienda de Autoservicio,Frescos y a granel,44,15.00,12.31,27.62,13.14,15.04,5.31,Nezahualcóyotl,40.01,Solidaridad,46.03,0.0,False
25,"Limón (1 kg, granel, agrio con semilla o colima)",Limón,1.0 kg,1 Kg. Granel. Agrio con Semilla o Colima,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,49,20.64,16.46,24.78,18.28,25.35,15.64,Ecatepec de Morelos,31.41,León,37.75,0.0,False
31,"Refresco Coca Cola (botella 1 lt, no retornable)",Refresco,1.0 l,Botella 1 Lt. No Retornable,Coca Cola,Supermercado / Tienda de Autoservicio,Bebidas,31,6.89,3.32,22.01,3.90,5.53,3.45,Tijuana,30.88,Coyoacán,33.00,0.0,False
9,"Calabaza (1 kg, granel, italiana/japonesa (larga))",Calabaza,1.0 kg,1 Kg. Granel. Italiana/japonesa (Larga),S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,43,35.46,29.29,49.17,29.70,33.24,7.37,La Paz,29.01,Hermosillo,39.40,0.0,False
40,"Refresco Squirt (botella 3 lt, no retornable)",Refresco,3.0 l,Botella 3 Lt. No Retornable,Squirt,Supermercado / Tienda de Autoservicio,Bebidas,31,7.64,3.57,9.37,2.47,3.91,4.45,Santiago de Querétaro,47.49,Centro,51.12,0.0,False
20,Huevo Bachoco (paquete c/12 blanco),Huevo,12.0 pieza,Paquete C/12 Blanco,Bachoco,Supermercado / Tienda de Autoservicio,Frescos y a granel,41,13.89,12.17,49.56,12.30,17.54,5.28,Tultitlán,28.11,Morelia,32.01,0.0,False
7,"Azúcar Zulka (bolsa plástico 2 kg, estándar o morena)",Azúcar,2.0 kg,Bolsa Plástico 2 Kg. Estándar o Morena,Zulka,Supermercado / Tienda de Autoservicio,Otros,36,4.56,2.96,13.36,3.41,4.58,0.68,Miguel Hidalgo,43.96,Juárez,45.94,0.0,False
44,"Yoghurt Alpura (vaso 120 gr, fresa)",Yoghurt,0.12 kg,Vaso 120 Gr. Fresa,Alpura,Supermercado / Tienda de Autoservicio,Otros,14,0.18,0.10,0.30,0.12,0.23,0.16,Benito Juárez (Ciudad de México),8.99,Centro,9.01,0.0,False
3,"Agua con Gas Del Valle (botella 600 ml, naranj-ada fizz)",Agua con Gas,0.6 l,Botella 600 Ml. Naranj-ada Fizz,Del Valle,Supermercado / Tienda de Autoservicio,Bebidas,30,33.99,18.75,49.90,22.42,29.95,13.25,Miguel Hidalgo,13.49,San Luis Potosí,17.97,0.0,False
12,Cerveza Barrilito (canasta con 6 botellas de 325 ml),Cerveza,0.325 l,Canasta con 6 Botellas de 325 Ml.,Barrilito,Supermercado / Tienda de Autoservicio,Bebidas,46,6.57,4.65,10.96,3.70,5.67,4.54,Durango,63.09,Azcapotzalco,67.25,0.0,False
28,"Papas Fritas y Similares Sabritas (bolsa 185 gr, churrumais, con l...",Papas Fritas y Similares,0.185 kg,Bolsa 185 Gr. Churrumais. con Limoncito,Sabritas,Supermercado / Tienda de Autoservicio,Otros,31,2.91,0.30,10.82,0.37,2.52,0.27,Culiacán,41.50,Juárez,42.71,0.0,False
18,Chícharos en Lata Del Monte (lata 200 gr),Chícharos en Lata,0.2 kg,Lata 200 Gr.,Del Monte,Supermercado / Tienda de Autoservicio,Otros,12,11.07,3.97,16.04,6.35,8.53,4.27,Saltillo,11.96,Solidaridad,13.31,0.0,False
8,"Bebidas Hidratantes Powerade (botella 1 lt, naranja)",Bebidas Hidratantes,1.0 l,Botella 1 Lt. Naranja,Powerade,Supermercado / Tienda de Autoservicio,Otros,45,28.57,21.97,30.46,23.28,26.02,12.95,Coacalco,26.10,Tlaxcala,33.97,0.0,False
2,"Agua con Gas Del Valle (botella 600 ml, limon-ada, fizz)",Agua con Gas,0.6 l,Botella 600 Ml. Limon-ada. Fizz,Del Valle,Supermercado / Tienda de Autoservicio,Bebidas,32,32.22,15.94,44.04,22.32,28.92,6.33,Iztapalapa,13.53,San Luis Potosí,17.97,0.0,False
10,"Camarón (1 kg, granel, chico, sin cabeza)",Camarón,1.0 kg,1 Kg. Granel. Chico. Sin Cabeza,S/M,Supermercado / Tienda de Autoservicio,Frescos y a granel,26,65.41,47.12,75.63,57.33,62.86,2.84,Durango,169.94,Coyoacán,275.57,0.0,False

**Conclusión.** De 1,238 artículos comparables, **45
(4%)** tienen una diferencia entre municipios que supera la prueba con control de falsos
positivos, y solo **21** con una diferencia de 10% o más claramente arriba del azar:
10 bebidas, 6 frescos, 2 de tortilla y 3 de otros
productos. En los que sobreviven, la misma cadena cobra 13% más en el municipio caro típico,
contra 1.3% en los demás. 93 artículos parecían distintos sin corregir y
no sobreviven.